# Generated by Django 5.1.4 on 2024-12-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
