# Generated by Django 4.2.7 on 2024-12-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_photo_url_team_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('points', 'Pontos'), ('rebounds', 'Rebotes'), ('assists', 'Assistências'), ('threes', 'Bolas de 3'), ('steals', 'Roubos'), ('blocks', 'Tocos')], max_length=20)),
                ('line', models.FloatField()),
                ('suggestion', models.CharField(max_length=5)),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], max_length=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_suggestions', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_suggestions', to='core.player')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('game', 'player', 'market')},
            },
        ),
    ]
