# Generated by Django 4.2.7 on 2024-12-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_betsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betsuggestion',
            name='market',
            field=models.CharField(choices=[('points', 'Pontos'), ('rebounds', 'Rebotes'), ('assists', 'Assistências'), ('steals', 'Roubos'), ('blocks', 'Bloqueios'), ('turnovers', 'Turnovers'), ('points_rebounds', 'Pontos + Rebotes'), ('points_assists', 'Pontos + Assistências'), ('points_assists_rebounds', 'Pontos + Assistências + Rebotes'), ('assists_rebounds', 'Assistências + Rebotes'), ('steals_blocks', 'Roubos + Bloqueios'), ('q1_points', 'Pontos no 1º Quarto'), ('q1_assists', 'Assistências no 1º Quarto'), ('q1_rebounds', 'Rebotes no 1º Quarto')], max_length=30),
        ),
    ]
