# Generated by Django 4.2.7 on 2024-12-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_betsuggestion_market'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betsuggestion',
            options={'ordering': ['game__date', 'player__last_name']},
        ),
        migrations.RemoveField(
            model_name='betsuggestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='playergamestats',
            name='team',
        ),
        migrations.AlterField(
            model_name='betsuggestion',
            name='market',
            field=models.CharField(choices=[('points', 'Pontos'), ('rebounds', 'Rebotes'), ('assists', 'Assistências'), ('steals', 'Roubos'), ('blocks', 'Bloqueios'), ('turnovers', 'Turnovers'), ('points_rebounds', 'Pontos + Rebotes'), ('points_assists', 'Pontos + Assistências'), ('points_assists_rebounds', 'Pontos + Assistências + Rebotes'), ('assists_rebounds', 'Assistências + Rebotes'), ('steals_blocks', 'Roubos + Bloqueios'), ('q1_points', 'Pontos no 1º Quarto'), ('q1_assists', 'Assistências no 1º Quarto'), ('q1_rebounds', 'Rebotes no 1º Quarto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='betsuggestion',
            name='suggestion',
            field=models.CharField(choices=[('over', 'Over'), ('under', 'Under')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Agendado'), ('Live', 'Ao Vivo'), ('Final', 'Finalizado'), ('Postponed', 'Adiado'), ('Cancelled', 'Cancelado')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
