# Generated by Django 4.2.7 on 2024-12-15 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_betsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betsuggestion',
            options={'ordering': ['-confidence', 'game__date', 'player__last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='betsuggestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='betsuggestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='betsuggestion',
            name='market',
            field=models.CharField(choices=[('points', 'Pontos'), ('assists', 'Assistências'), ('rebounds', 'Rebotes'), ('points_rebounds_assists', 'Pontos + Rebotes + Assistências')], max_length=50),
        ),
    ]
