# Generated by Django 4.2.7 on 2024-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_betsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betsuggestion',
            name='hit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betsuggestion',
            name='odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='betsuggestion',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
